name: Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Test
                run: mkdir ./build/one -p && echo "Hello World (1)" > ./build/one/index.html
            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: app-build
                    path: ./build
    deploy:
        needs: [build]
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            contents: "read"
            id-token: "write"
            pages: "write"
            actions: "write"
            checks: "write"
            deployments: "write"
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Download build artifact
                uses: actions/download-artifact@v4
                with:
                    name: app-build
                    path: ./build
            -   name: Setup pages
                uses: actions/configure-pages@v5
            -   name: Upload artifacts
                uses: actions/upload-pages-artifact@v3
                with:
                    path: "./build"
            -   name: Deploy to GitHub-Pages
                uses: actions/deploy-pages@v4
                id: deployment
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
